create a new branch Books module
alevgn/LibraryAppDB_Assignments pull request #4
Opened 2023-03-28 16:12 UTC by Mariagirbu

New branch MG

2023-03-28 20:38 UTC, nurseda916 approved these changes

2023-03-30 01:42 UTC, farukgoc requested changes
There is no implementation on your step definitions. Why?

2023-03-30 01:42 UTC, farukgoc commented on src/test/resources/features/B28G31-151_MG.feature
> +
@ui @db

2023-03-30 15:03 UTC, farukgoc approved these changes
Good job Maria

2023-03-30 15:04 UTC, untuzina approved these changes

2023-03-30 15:06 UTC, alevgn approved these changes
Looks good!

2023-03-30 15:16 UTC, merged